version: '3.9'

services:
  frontend:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3030:3000"
    command: sh -c "npm run dev"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "flavor-swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./api/bundle.json:/bundle.json
    environment:
      SWAGGER_JSON: /bundle.json

  # swagger-api:
  #   image: stoplight/prism:3
  #   container_name: "swagger-api"
  #   ports:
  #     - "8003:4010"
  #   command: mock -h 0.0.0.0 /openapi.yaml
  #   volumes:
  #     - ./api/openapi.yaml:/openapi.yaml
